version: '3.3'

services:
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - traefik-webnet
    ports:
      - "8123:8123"
      - "80:80"
      - "8080:8080"
      - "2015:2015"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/home/pi/labdev/traefik/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant
    networks:
    - traefik-webnet
    volumes:
      - homeassistantconfig:/config
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      labels:
     #    - "traefik.backend.loadbalancer.stickiness=true"
#         - "traefik.backend.loadbalancer.swarm=true"
#         - "traefik.backend=homeassistant"
         - "traefik.frontend.rule=Host:${dominio}"
         - "traefik.docker.network=homeassistant_traefik-webnet" 
         - "traefik.port=8123"
         - "traefik.enable=true"

  nginx:
    image: nginx
    networks:
    - traefik-webnet 
    deploy:
      mode: replicated
      labels:
         - "traefik.frontend.rule=Host:${dominio};PathPrefixStrip:/nginx"
         - "traefik.docker.network=nginx_traefik-webnet"
         - "traefik.port=80"
         - "traefik.enable=true"

  caddy:
    image: xaviaznar/rpi-alpine-caddy:v1.0 
    networks:
    - traefik-webnet
    deploy:
#      replicas: 2  
      labels:
      - "traefik.frontend.rule=Host:${dominio};PathPrefixStrip:/caddy"
      - "traefik.docker.network=caddy_traefik-webnet"
      - "traefik.port=2015"
      - "traefik.enable=true"

networks:
  traefik-webnet:
    driver: overlay

volumes:
  homeassistantconfig:
