version: '3.3'

services:
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=traefik \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - traefik-webnet
    ports:
      - "8123:8123"
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/home/pi/labdev/traefik/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]

  homeassistant:
     image: homeassistant/raspberrypi3-homeassistant
     networks:
       - traefik-webnet
     volumes:
       - homeassistantconfig:/config
       - /etc/localtime:/etc/localtime:ro
     deploy:
       mode: replicated
       labels:
#         - "traefik.enable=true"
     #    - "traefik.backend.loadbalancer.stickiness=true"
#         - "traefik.backend.loadbalancer.swarm=true"
         - "traefik.backend=homeassistant"
         - "traefik.docker.network=homeassistant_traefik-webnet"
         - "traefik.frontend.rule=Host:openlab.dynip.sapo.pt"
         - "traefik.port=8123"
networks:
  traefik-webnet:
    driver: overlay

volumes:
  homeassistantconfig:
